name: Markdown Lint

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install markdownlint
        run: |
          npm install -g markdownlint-cli

      - name: Lint markdown files
        run: |
          markdownlint "**/*.md" --config .markdownlint.json
