name: YAML Lint

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Lint YAML files
        run: |
          yamllint -c .yamllint .
        continue-on-error: true

      - name: Check YAML syntax
        run: |
          find . -name "*.yml" -o -name "*.yaml" | grep -v "invidious/templates/" | while read -r file; do
            echo "Checking $file..."
            python -c "import yaml; yaml.safe_load(open('$file', 'r'))"
          done
